### ISSUE TITLE
Eliminar _trailing spaces_

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/trabalho-adventure#1]
Código tem muitos _trailing spaces_, e, caso os alunos usem formatação automática para corrigir isso, acabam surgindo muitas alterações desnecessárias no commit, que prejudicam a correção/feedback.

Seria ideal já corrigir isso no código fornecido.

**Comment by vitorfn** [comment]
Olá, @caburu, boa tarde! Meu grupo irá trabalhar nessa issue.
