### ISSUE TITLE
Usar tipos enumeradores

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/trabalho-adventure#2]
O jogo utiliza strings para informações que seriam melhor representadas por tipos enumeradores.

No material do livro do Barnes e Kolling isso é tratado. Seria interessante já trazer para a versão inicial do código.

**Comment by Nxxxlxs** [comment]
Olá @caburu, gostaria de trabalhar nessa issue. Caso possível, poderia detalhar um pouco mais o que deve ser alterado para tipo enumerador?

**Comment by caburu** [comment]
Olá @Nxxxlxs, bacana que está interessado em ajudar nesta issue.

A ideia seria tratar os comandos do jogo (ir, sair e ajuda) como um enumerador. E também as possíveis direções (norte, leste, oeste, sul) como outro tipo enumerador.
- É importante também que os enumeradores tenham um atributo com sua representação como String e o retornem no método `toString`.

O código desse trabalho é baseado no livro *Programação Orientada a Objetos com Java* de Barnes e Kolling. O enumerador para tratar os comandos do jogo é apresentado no livro, na Seção 7.13, e o livro está disponível na Biblioteca Virtual. Portanto, seria interessante se basear no código apresentado lá (basta traduzir os códigos para Português).

Qualquer dúvida, estou à disposição.

**Comment by lyviaAbreu** [comment]
Vamos coolaborar também, não para substituir o que o grupo fez, mas para acrescentar

**Comment by caburu** [comment]
Olá @lyviaAbreu, bacana estarem interessados em contribuir com o repositório.

Como é um projeto bem simples, não há um procedimento formal de contribuições. Mas vi que fez falta ter uma orientação inicial.

O ideal seria primeiro se disponibilizar para fazer as alterações e aguardar meu retorno para só então fazer as implementações. Isso para evitar o que acabou acontecendo: outras pessoas já tinham se disponibilizado a fazer as alterações antes, e, agora, não consigo absorver as alterações de todos.

Vou fazer comentários específicos nos Pull Requests que vocês enviaram e, para que consigam contribuir, minha sugestão é que tratem as direções do jogo como um tipo enumerador (vou abrir uma nova Issue sobre isso com mais detalhes). Caso tenham interesse, peço que se manifestem nessa nova Issue sobre como pretendem resolver e, aguardem o meu retorno, e só depois disso façam a implementação. A ideia não é criar burocracia, mas sim evitar que tenham retrabalho com as contribuições ;)

Qualquer dúvida, estou à disposição.
